# Generated by Django 3.2.6 on 2021-11-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FRdata2',
            fields=[
                ('Username', models.CharField(default=True, max_length=100, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='pics')),
                ('Password', models.IntegerField()),
            ],
        ),
    ]
